name: "Component Builder"
on:
  pull_request:
  pull_request_target:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  guest-fedora-amd64:
    runs-on: ubuntu-latest
    env:
      FEDORA_IMAGE: Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2
      FEDORA_VERSION: 41
      CPU_ARCH: amd64
      FULL_EMULATION: "true"
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: check nest virt
        run: |
          set -xe
          is_nested_virt_enabled() {
            local kvm_nested="unknown"
            if [ -f "/sys/module/kvm_intel/parameters/nested" ]; then
               kvm_nested=$( cat /sys/module/kvm_intel/parameters/nested )
            elif [ -f "/sys/module/kvm_amd/parameters/nested" ]; then
              kvm_nested=$( cat /sys/module/kvm_amd/parameters/nested )
            fi
            [ "$kvm_nested" == "1" ] || [ "$kvm_nested" == "Y" ] || [ "$kvm_nested" == "y" ]
          }
          is_nested_virt_enabled
